services:
  # Backend Symfony
  backend:
    build:
      context: ./backend-sis
      dockerfile: Dockerfile
    container_name: sis-backend
    restart: unless-stopped
    volumes:
      - ./backend-sis:/var/www/html
    ports:
      - "4000:8000"
    depends_on:
      - database
      - minio
      - keycloak
    environment:
      APP_ENV: dev
      APP_SECRET: a660bec2b10af5b8f8c12dfb6d3e0428
      DATABASE_URL: mysql://root:password@database:3306/backend_sis?serverVersion=8.0
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/symfony-app
      KEYCLOAK_CLIENT_ID: symfony-app
      KEYCLOAK_CLIENT_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_REALM: symfony-app
      PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      MAILER_DSN: smtp://mailer:1025
    networks:
      - sis-network

  # Frontend Patient-Mobile
  frontend-patient-mobile:
    build:
      context: ./frontend-sis-patient-mobile
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://patient-mobile-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    container_name: sis-frontend-patient-mobile
    restart: unless-stopped
    ports:
      - "4001:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://patient-mobile-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    networks:
      - sis-network

  # Frontend Doctor
  frontend-doctor:
    build:
      context: ./frontend-sis-doctor
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://medecin-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_PUBLISHABLE_KEY: ${NEXT_PUBLIC_PUBLISHABLE_KEY:-your-publishable-key-here}
    container_name: sis-frontend-doctor
    restart: unless-stopped
    ports:
      - "4002:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://medecin-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_PUBLISHABLE_KEY: ${NEXT_PUBLIC_PUBLISHABLE_KEY:-your-publishable-key-here}
    networks:
      - sis-network

  # Frontend Admin
  frontend-admin:
    build:
      context: ./frontend-sis-admin
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://admin-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    container_name: sis-frontend-admin
    restart: unless-stopped
    ports:
      - "4003:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://admin-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    networks:
      - sis-network

  # Frontend Admin Hospital
  frontend-admin-hospital:
    build:
      context: ./frontend-sis-admin-hospital
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://admin-hopital-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
    container_name: sis-frontend-admin-hospital
    restart: unless-stopped
    ports:
      - "4004:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://admin-hopital-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
    networks:
      - sis-network

  # Frontend Agent Accueil
  frontend-agent-accueil:
    build:
      context: ./frontend-sis-agent-accueil
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://agent-accueil-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    container_name: sis-frontend-agent-accueil
    restart: unless-stopped
    ports:
      - "4005:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://agent-accueil-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    networks:
      - sis-network

  # Frontend Urgence
  frontend-urgence:
    build:
      context: ./frontend-sis-urgence
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://urgence-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: hhttp://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: hhttp://patient-desktop-sis.webtinix.com
    container_name: sis-frontend-urgence
    restart: unless-stopped
    ports:
      - "4006:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://urgence-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
    networks:
      - sis-network

  # Frontend Patient-Desktop
  # This service is for the desktop version of the patient frontend
  frontend-patient-desktop:
    build:
      context: ./frontend-sis-patient-desktop
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: your-secret-key-here
        NEXTAUTH_URL: http://patient-desktop-sis.webtinix.com
        API_URL: http://backend:8000/api/v1
        KEYCLOAK_ID: symfony-app
        KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
        KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_USE_SSL: "false"
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        MINIO_BUCKET: default-bucket
        NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
        NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
        NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
        NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
        DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
        NEXT_PUBLIC_PUBLISHABLE_KEY: ${NEXT_PUBLIC_PUBLISHABLE_KEY:-your-publishable-key-here}
    container_name: sis-frontend-patient-desktop
    restart: unless-stopped
    ports:
      - "40013:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: your-secret-key-here
      NEXTAUTH_URL: http://patient-desktop-sis.webtinix.com
      API_URL: http://backend:8000/api/v1
      KEYCLOAK_ID: symfony-app
      KEYCLOAK_SECRET: 52c0e07c-449b-4979-8561-76770f00730a
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/symfony-app
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: default-bucket
      NEXT_PUBLIC_PUSHER_APP_ID: ${PUSHER_APP_ID:-1990615}
      NEXT_PUBLIC_PUSHER_KEY: ${PUSHER_APP_KEY:-45d6d619dfbddef2cb98}
      NEXT_PUBLIC_PUSHER_SECRET: ${PUSHER_APP_SECRET:-66154ba4647bd873e612}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${PUSHER_APP_CLUSTER:-eu}
      DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_DESKTOP_APP_URL: http://patient-desktop-sis.webtinix.com
      NEXT_PUBLIC_PUBLISHABLE_KEY: ${NEXT_PUBLIC_PUBLISHABLE_KEY:-your-publishable-key-here}
    networks:
      - sis-network

  # Base de données MySQL
  database:
    image: mysql:8.0
    container_name: sis-database
    restart: unless-stopped
    ports:
      - "4007:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_sis
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - sis-network

  # PhpMyAdmin pour la gestion de la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sis-phpmyadmin
    restart: unless-stopped
    ports:
      - "4013:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    depends_on:
      - database
    networks:
      - sis-network

  # Keycloak pour l'authentification
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: sis-keycloak
    restart: unless-stopped
    ports:
      - "4008:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://database:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command:
      - start-dev
    depends_on:
      - database
    networks:
      - sis-network

  # Minio pour le stockage d'objets
  minio:
    image: minio/minio
    container_name: sis-minio
    restart: unless-stopped
    ports:
      - "4009:9000"  # API
      - "4010:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - sis-network

  # Service de mail pour le développement
  mailer:
    image: axllent/mailpit
    container_name: sis-mailer
    restart: unless-stopped
    ports:
      - "4011:1025"  # SMTP
      - "4012:8025"  # Interface web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - sis-network

volumes:
  mysql-data:
  minio-data:

networks:
  sis-network:
    driver: bridge